### ISSUE TITLE
FFM: Getting NaN in tr_loss

### ISSUE THREAD

**Issue by arashidbd** [Intel-bigdata/imllib-spark#10]
`numFields:12,nunFeatures:156641,numFactors:11`

18M rows of data. #of partitions: 60

Basically `lSum` is coming out as `NaN`

`libFFM` handles the dataset w/o issues.

Any clues?
Thanks,
Al

**Comment by VinceShieh** [comment]
we cannot root cause the issue with the information you provided. Could you share the dataset under test?

**Comment by VinceShieh** [comment]
please gv back to us if u find the issue is related to the model. thanks.

**Comment by kapilkd13** [comment]
I am getting the same issue. has anyone found a fix
