### ISSUE TITLE
Support for Spark ML Pipelines

### ISSUE THREAD

**Issue by kumarmsingh** [Intel-bigdata/imllib-spark#15]
Currently these APIs are low level RDD based. Is there any plan to implement them as Dataset/Dataframe based API, so that it can work with Spark ML Piplelines?

**Comment by VinceShieh** [comment]
Yes, it's on our plan. Currently, there are some issues regarding the task since we need to be compatible with the previous Spark releases and at the same time not breaking the build.

**Comment by VinceShieh** [comment]
currently, we don't have the bandwidth to work on that, we will discuss on that. Meanwhile, you are welcome to work with us on this implementation by submitting PRs. Thanks.
