### ISSUE TITLE
is this project compatible to scala 2.10 and spark 1.6?

### ISSUE THREAD

**Issue by luowenjuan** [Intel-bigdata/imllib-spark#2]

**Comment by VinceShieh** [comment]
yes.

**Comment by luowenjuan** [comment]
how many features could this algorithm handle? I have got a dataset of numFields:2771,numFeatures:1868882
when I run the project, the optimization.GradientDescentFFM just ran out of memory.
It seems that the "data.treeAggregate(BDV(bcWeights.value.toArray), 0.0)"  just uses a huge amount of memory.

**Comment by VinceShieh** [comment]
in this case with numFields:2771,numFeatures:1868882, and given the k factor as 2, it would be about 10GB for a single weight vector, it's too much for spark to handle.
I think there will be problem to initialize the weight vector at the very beginning in your case.

as for memory limitation, if the weight vector can be fit into 4GB length, it will depends on your cluster configurations. Also you can tune the tree depth to alleviate the pressure on driver node.

**Comment by luowenjuan** [comment]
yes, the variable position becomes out of bound, I changed the code a little to avoid the mistake, however, later it goes OOM.

**Comment by VinceShieh** [comment]
okay. So in this case, there are three options: 1. look into your data, optimize the field setting to control the feature interactions 2. increase the device memory and increase the tree depth 3. parameter server.
