### ISSUE TITLE
CRF. Line based features (instead of word based features) wtih Regular Expressions

### ISSUE THREAD

**Issue by REASY** [Intel-bigdata/imllib-spark#7]
Let's imagine that we have set of emails and we want to detect signature part in these emails. Common Random Fields shows very good accuracy for this task (due to [Learning to Extract Signature and Reply Lines from Email](http://www.cs.cmu.edu/~wcohen/postscript/email-2004.pdf).
My features might be:

- Line contains email pattern;
- Line contains URL pattern;
- Line contains phone number pattern;
- Line contains 'best regards', 'yours faithfully', 'yours sincerely' and etc;
- Line contains the name of the message sender, surname, or both;
- Line matches the regular expression "^[\s]*---*[\s]*$";
- etc;
Is it possible to describe line based features in template? Is it possible to use regular expressions in templates?

**Comment by hqzizania** [comment]
in common crf applications（such as shallow parsing) for NLP, a sequence for probability states chain represents as a sentence. The paper you posted above tell us a sequence represents as a email with multi lines. 
Sorry for lackness of a general input Method for features here.
You need do some feature transforming by yourself before using this crf project, whether line based transformed to word based (paragraph or mail -> a line) or transform feature via regular expressions.

**Comment by REASY** [comment]
@hqzizania, I've got it, thanks.
